[meshsmith_photon_nrf]
extends = nrf52_base
board = seeed-xiao-afruitnrf52-nrf52840
board_build.ldscript = boards/nrf52840_s140_v7.ld
build_flags = ${nrf52_base.build_flags}
  -I lib/nrf52/s140_nrf52_7.3.0_API/include
  -I lib/nrf52/s140_nrf52_7.3.0_API/include/nrf52
  -I variants/meshsmith_photon_nrf
  -I variants/xiao_nrf52
  -D NRF52_PLATFORM
  -D NRF52_POWER_MANAGEMENT
  -D XIAO_NRF52
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=18
  -D P_LORA_TX_LED=11
  -D P_LORA_DIO_1=D0
  -D P_LORA_RESET=D1
  -D P_LORA_BUSY=D2
  -D P_LORA_NSS=D3
  -D SX126X_RXEN=RADIOLIB_NC
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D PIN_WIRE_SDA=D4
  -D PIN_WIRE_SCL=D5
  -D PIN_USER_BTN=PIN_BUTTON1
  -D PIN_GPS_TX=D7
  -D PIN_GPS_RX=D6
  -D GPS_BAUD_RATE=115200
  -D ENV_SKIP_GPS_DETECT=1
  -D PERSISTANT_GPS=1
  -D ENV_INCLUDE_GPS=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<../variants/meshsmith_photon_nrf>
  +<../variants/xiao_nrf52/variant.cpp>
debug_tool = jlink
upload_protocol = nrfutil
lib_deps =
  ${nrf52_base.lib_deps}
  stevemarple/MicroNMEA @ ^2.0.6
  adafruit/Adafruit AHTX0 @ ^2.0.5
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit BMP280 Library @ ^2.6.8
  adafruit/Adafruit INA219 @ ^1.2.3
  adafruit/Adafruit INA260 Library @ ^1.5.3
  adafruit/Adafruit SHTC3 Library @ ^1.0.1
  adafruit/Adafruit_VL53L0X @ ^1.2.4
  sensirion/Sensirion I2C SHT4x @ ^1.1.2

[meshsmith_photon_nrf_repeater]
extends = meshsmith_photon_nrf
build_src_filter = ${meshsmith_photon_nrf.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
build_flags =
  ${meshsmith_photon_nrf.build_flags}
  -D ADVERT_NAME='"Photon NRF Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps =
  ${meshsmith_photon_nrf.lib_deps}

[env:meshsmith_photon_nrf_repeater]
extends = meshsmith_photon_nrf_repeater

[env:meshsmith_photon_nrf_companion_radio_ble]
extends = meshsmith_photon_nrf
board_build.ldscript = boards/nrf52840_s140_v7_extrafs.ld
board_upload.maximum_size = 708608
build_flags =
  ${meshsmith_photon_nrf.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D ENABLE_PRIVATE_KEY_IMPORT=1
  -D ENABLE_PRIVATE_KEY_EXPORT=1
  -D QSPIFLASH=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${meshsmith_photon_nrf.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio/*.cpp>
lib_deps =
  ${meshsmith_photon_nrf.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:meshsmith_photon_nrf_kiss_modem]
extends = meshsmith_photon_nrf
build_src_filter = ${meshsmith_photon_nrf.build_src_filter}
  +<../examples/kiss_modem/>
